### ISSUE TITLE
Stream Error: "malformed-request"

### ISSUE THREAD

**Issue by kagulik** [fabiang/xmpp#68]
I am trying to send message.
Here is xmpp_send_mes.php : 
``` php
require __DIR__ . '/vendor/autoload.php';

use Fabiang\Xmpp\Options;

$address = 'tcp://[address]:5222';
$username = [username];
$password = [pass];

$options = new Options($address);
$options->setUsername($username)
        ->setPassword($password);

use Fabiang\Xmpp\Client;
$client = new Client($options);
// optional connect manually
$client->connect();

use Fabiang\Xmpp\Protocol\Roster;
use Fabiang\Xmpp\Protocol\Presence;
use Fabiang\Xmpp\Protocol\Message;

// fetch roster list; users and their groups
$client->send(new Roster);
// set status to online
$client->send(new Presence);

// send a message to another user
$message = new Message;
$message->setMessage('test')
        ->setTo('*****');
$client->send($message); 

$client->disconnect();
```

---

What I get in terminal : 
``` terminal
user@PC:/var/www/site1$ php -f xmpp_send_mes.php
PHP Fatal error:  Uncaught Fabiang\Xmpp\Exception\Stream\AuthenticationErrorException: Stream Error: "malformed-request" in /var/www/site1/vendor/fabiang/xmpp/src/Exception/Stream/StreamErrorException.php:77
Stack trace:
#0 /var/www/site1/vendor/fabiang/xmpp/src/EventListener/Stream/Authentication.php(163): Fabiang\Xmpp\Exception\Stream\StreamErrorException::createFromEvent(Object(Fabiang\Xmpp\Event\XMLEvent))
#1 [internal function]: Fabiang\Xmpp\EventListener\Stream\Authentication->failure(Object(Fabiang\Xmpp\Event\XMLEvent))
#2 /var/www/site1/vendor/fabiang/xmpp/src/Event/EventManager.php(126): call_user_func(Array, Object(Fabiang\Xmpp\Event\XMLEvent))
#3 /var/www/site1/vendor/fabiang/xmpp/src/Stream/XMLStream.php(362): Fabiang\Xmpp\Event\EventManager->trigger('{urn:ietf:param...', Object(Fabiang\Xmpp\Stream\XMLStream), Array)
#4 /var/www/site1/vendor/fabiang/xmpp/src/Stream/XMLStream.php(163): Fabiang\Xmpp\Stream\XMLStream->trigger()
#5 /var/www/site1/vendor/fabiang/xmpp/src/Connection/Socket.php(109): Fabiang\Xmpp\Stream\X in /var/www/site1/vendor/fabiang/xmpp/src/Exception/Stream/StreamErrorException.php on line 77

```

What do I do wrong?

**Comment by simplerezo** [comment]
Would have been nice to explain how you fixed this !

I had the same issue, and my mistake was to use XMPP username with the domain (@domain.com).

**Comment by youmad** [comment]
> Would have been nice to explain how you fixed this !
> 
> I had the same issue, and my mistake was to use XMPP username with the domain (@domain.com).

Open new issue, please, and descibe your problem in detail. Please, don't forget to put your configuration.

**Comment by simplerezo** [comment]
> Open new issue, please, and descibe your problem in detail. Please, don't forget to put your configuration.

???

My "issue" has been fixed... Just by using username WITHOUT domain.
